---
title: "Rishi's Git"
date: 2018-10-28
---

title: Never Say Never
author: Ranjan Rishi Chambial
email: cranjanrishi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Rishi's World!

# social links

github_username:  https://github.com/Rish619

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
